# Generated by Django 4.1.2 on 2022-10-24 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField(default='', verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('count_messages', models.IntegerField(default=0, verbose_name='Суммарное число сообщений')),
                ('companion_first', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comp_first', to=settings.AUTH_USER_MODEL, verbose_name='Собеседник 1')),
                ('companion_second', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comp_sec', to=settings.AUTH_USER_MODEL, verbose_name='Собеседник 2')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
            },
        ),
    ]
