# Generated by Django 4.1.2 on 2022-10-30 22:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_api', '0002_alter_chats_companion_second'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='companion_first',
        ),
        migrations.RemoveField(
            model_name='chats',
            name='companion_second',
        ),
        migrations.AddField(
            model_name='chats',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='chats',
            name='users',
            field=models.ManyToManyField(related_name='chat_users', to=settings.AUTH_USER_MODEL,
                                         verbose_name='Пользователи чата'),
        ),
    ]
