# Generated by Django 4.1.2 on 2022-10-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chat_api', '0004_alter_chats_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='topic',
            field=models.TextField(default='Базовое название', verbose_name='Название'),
        ),
    ]
