# Generated by Django 4.1.2 on 2022-11-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0007_alter_chat_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='description',
            field=models.TextField(default='Базовое описание', max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='topic',
            field=models.TextField(default='Базовое название', max_length=100, verbose_name='Название'),
        ),
    ]
