# Generated by Django 4.1.2 on 2022-10-31 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chat_api', '0003_remove_chats_companion_first_and_more'),
        ('chat_message_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='messages_in_chat', to='chat_api.chats',
                                    verbose_name='Идентификатор чата'),
        ),
    ]
