# Generated by Django 4.1.2 on 2022-10-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chat_message_api', '0002_alter_messages_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='viewed',
            field=models.BooleanField(default=False, verbose_name='Просмотрено ли сообщение'),
        ),
    ]
