# Generated by Django 4.1.2 on 2022-11-02 16:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0006_rename_chats_chat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_message_api', '0003_messages_viewed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
