# Generated by Django 4.1.2 on 2022-11-08 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_message_api', '0004_rename_messages_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['dispatch_date'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
