# Generated by Django 4.1.2 on 2022-11-08 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_message_api', '0005_alter_message_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(max_length=75, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_of_msgs', to=settings.AUTH_USER_MODEL, verbose_name='Автор сообщения'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, max_length=100, verbose_name='Содержимое сообщения'),
        ),
    ]
