# Generated by Django 4.1.2 on 2022-10-23 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat_api', '0005_alter_user_last_seen_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='Содержимое сообщения')),
                ('dispatch_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_of_msgs', to=settings.AUTH_USER_MODEL, verbose_name='Автор сообщения')),
                ('chat_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_in_chat', to='chat_api.chats', verbose_name='Идентификатор чата')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
