# Generated by Django 4.1.2 on 2022-10-15 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.TextField()),
                ('password', models.TextField()),
                ('email', models.TextField(blank=True)),
                ('phone_number', models.TextField(blank=True)),
                ('premium_status', models.BooleanField(default=False)),
                ('registration_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.TextField(default='')),
                ('count_messages', models.IntegerField(default=0)),
                ('companion_first',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comp_first',
                                   to='chat_api.users')),
                ('companion_second',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comp_set',
                                   to='chat_api.users')),
            ],
        ),
    ]
