# Generated by Django 4.1.2 on 2022-10-19 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='companion_first',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comp_first', to=settings.AUTH_USER_MODEL, verbose_name='Собеседник 1'),
        ),
        migrations.AlterField(
            model_name='chats',
            name='companion_second',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comp_set', to=settings.AUTH_USER_MODEL, verbose_name='Собеседник 2'),
        ),
        migrations.AlterField(
            model_name='chats',
            name='count_messages',
            field=models.IntegerField(default=0, verbose_name='Суммарное число сообщений'),
        ),
        migrations.AlterField(
            model_name='chats',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_seen_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата последнего посещения ресурса'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.TextField(blank=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='premium_status',
            field=models.BooleanField(default=False, verbose_name='Премиум статус'),
        ),
    ]
