# Generated by Django 4.1.2 on 2022-10-15 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
