# Generated by Django 4.1.2 on 2022-10-19 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0002_alter_chats_companion_first_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='companion_second',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comp_seс', to=settings.AUTH_USER_MODEL, verbose_name='Собеседник 2'),
        ),
    ]
