# Generated by Django 4.1.2 on 2022-11-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_user', '0002_user_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Online'),
        ),
    ]
