# Generated by Django 4.1.2 on 2022-12-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_user', '0004_user_is_user_logged_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='csrf_token',
            field=models.TextField(default='', null=True, verbose_name='Токен пользователя'),
        ),
    ]
